### ISSUE TITLE
"Frecency_update" ping is generated when visiting website from History (or Bookmarks) in Private Mode 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [florian/federated-learning-addon#7]
[Affected versions]:
- Firefox 62.0b6

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a new Firefox profile with the latest version of the "Federated Learning" add-on installed.
- Have the 'extensions.legacy.enabled' pref set to 'true'.
- History is populated with visited websites.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the "Hamburger menu" button>New Private Window.
3. Type the 1st character of a previously visited website in the Address bar 
4. Click on the previously visited website from the suggestions list.
4. Go to "about:telemetry" page and observe if any pings were generated.

[Expected result]:
- No pings are generated when visiting again websites on Private Mode.

[Actual result]:
- "Frecency_update" ping is generated.

[Additional Notes]:
- We logged the current issue since (as per the email thread) we decided that the experiment shouldn't run in Private Mode.
- The ping is also sent to the local server we previously set.
- This issue is reproducible on all the 3 branches.
- Attached a screen recording of the issue:

![private mode](https://user-images.githubusercontent.com/26000308/42523367-3873b712-8476-11e8-8e0c-0313f063c2fb.gif)

**Comment by florian** [comment]
This should now be fixed, as of ddac936add0c369b869da4ed3f34f6663abbc044.

**Comment by SoftVision-CarmenFat** [comment]
Tested this with the latest .xpi from the email and the issue is still reproducible. The "frecency" ping is still generated and sent to the local server when visiting websites from History, while in Private Mode.

**Comment by florian** [comment]
Oh yeah, that build didn't include the fix yet.
I wanted to send you another build with this and the fix for the study ending bug but didn't manage to do that yesterday.
Sorry for the confusion.

**Comment by florian** [comment]
@SoftVision-CarmenFat I've sent you an email with a new build that should hopefully fix this issue.
